# server settings
server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /
  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs
logging:
  config: classpath:logback.xml
  level:
    org.springwork: ERROR
    com.hades: DEBUG
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  jpa:
    persistenceUnitName: jpa.es.web
    generateDdl: true
    database: MYSQL
    showSql: true
    hibernate.ddl-auto: update
    hibernate.implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategy
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true

# Shiro 配置
shiro:
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /unauthorized